apiVersion: v1 
kind: PersistentVolume
metadata:
  name: db-persistent-volume
spec:
  storageClassName: dbstorage
  capacity:
    storage: 10Gi #we are consuming 10gi of storage. but this is thin provisioning. 
  accessModes: 
      - ReadWriteOnce #readwritemany #read
  hostPath:
      path: /mnt/db/data
